[tools]
lua-language-server = "latest"
neovim = "latest"
node = { version = "lts", postinstall = "corepack enable" }
zig = "latest"
lazygit = "latest"
delta = "latest"
github-cli = "latest"
yazi = "latest"
ripgrep = "latest"
fzf = "latest"
zoxide = "latest"
starship = "latest"
lazydocker = "latest"
"github:chojs23/ec" = "latest"

[settings]
auto_update = true
