[tools]
lua-language-server = "latest"
neovim = "latest"
node = { version = "lts", postinstall = "corepack enable" }		
zig = "latest"
lazygit = "latest"
delta = "latest"
github-cli = "latest"
yazi = "latest"

[settings]
auto_update = true
