
[tools]
lua-language-server = "latest"
neovim = "latest"
node = { version = "lts", postinstall = "corepack enable" }
zig = "latest"
lazygit = "latest"
delta = "latest"
github-cli = "latest"
yazi = "latest"
ripgrep = "latest"
fzf = "latest"
zoxide = "latest"
starship = "latest"

[settings]
auto_update = true

[bootstrap.repos]
"C:/repos/iplicit" = { url = "https://github.com/iplicit/iplicit", ref = "master" }
"C:/repos/analytics" = { url = "https://github.com/iplicit/analytics", ref = "main" }
"C:/repos/authentication" = { url = "https://github.com/iplicit/authentication", ref = "main" }
"C:/repos/build-shared" = { url = "https://github.com/iplicit/build-shared", ref = "main" }
"C:/repos/client-manager" = { url = "https://github.com/iplicit/client-manager", ref = "main" }
"C:/repos/common" = { url = "https://github.com/iplicit/common", ref = "main" }
"C:/repos/databases-domains" = { url = "https://github.com/iplicit/databases-domains", ref = "main" }
"C:/repos/document-analysis" = { url = "https://github.com/iplicit/document-analysis", ref = "main" }
"C:/repos/email-service" = { url = "https://github.com/iplicit/email-service", ref = "main" }
"C:/repos/execution-service" = { url = "https://github.com/iplicit/execution-service", ref = "main" }
"C:/repos/iplicit-doc" = { url = "https://github.com/iplicit/iplicit-doc", ref = "main" }
"C:/repos/iplicit-electron" = { url = "https://github.com/iplicit/electron", ref = "master" }
"C:/repos/iplicit-excel" = { url = "https://github.com/iplicit/excel", ref = "master" }
"C:/repos/mobile-app" = { url = "https://github.com/iplicit/mobile-app", ref = "main" }
"C:/repos/mobile-service" = { url = "https://github.com/iplicit/mobile-service", ref = "main" }
"C:/repos/mtd-portal" = { url = "https://github.com/iplicit/mtd-portal", ref = "master" }
"C:/repos/partner-portal-doc" = { url = "https://github.com/iplicit/partner-portal-doc", ref = "main" }
"C:/repos/payment-services" = { url = "https://github.com/iplicit/payment-services", ref = "main" }
"C:/repos/print-agent" = { url = "https://github.com/iplicit/print-agent", ref = "main" }
"C:/repos/public-api" = { url = "https://github.com/iplicit/public-api", ref = "main" }
"C:/repos/tool-db-sync" = { url = "https://github.com/iplicit/tool-db-sync", ref = "main" }
"C:/repos/tools" = { url = "https://github.com/iplicit/tools", ref = "main" }
